name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Model Training (Generate artifact for tests)
        run: uv run python -m src.train

      - name: Run API Tests
        # Definition of variable env so test can find generated model
        env:
          LOCAL_MODEL_PATH: "mlruns/1/models/m-c904336239504334adc31d5c3b6dc924/artifacts"
        run: uv run pytest tests/test_api.py
